
package fr.afcepf.atod.ws.soap.shipping;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Exception", targetNamespace = "shipping.soap.ws.atod.afcepf.fr")
public class Exception_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private fr.afcepf.atod.ws.soap.shipping.Exception faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Exception_Exception(String message, fr.afcepf.atod.ws.soap.shipping.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Exception_Exception(String message, fr.afcepf.atod.ws.soap.shipping.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fr.afcepf.atod.ws.soap.shipping.Exception
     */
    public fr.afcepf.atod.ws.soap.shipping.Exception getFaultInfo() {
        return faultInfo;
    }

}
