
package fr.afcepf.atod.ws.soap.shipping;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapShippingServiceService", targetNamespace = "shipping.soap.ws.atod.afcepf.fr", wsdlLocation = "http://localhost:28080/SOAPShipping-1.0.0/shippingCheckout?wsdl")
public class SoapShippingServiceService
    extends Service
{

    private final static URL SOAPSHIPPINGSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPSHIPPINGSERVICESERVICE_EXCEPTION;
    private final static QName SOAPSHIPPINGSERVICESERVICE_QNAME = new QName("shipping.soap.ws.atod.afcepf.fr", "SoapShippingServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:28080/SOAPShipping-1.0.0/shippingCheckout?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPSHIPPINGSERVICESERVICE_WSDL_LOCATION = url;
        SOAPSHIPPINGSERVICESERVICE_EXCEPTION = e;
    }

    public SoapShippingServiceService() {
        super(__getWsdlLocation(), SOAPSHIPPINGSERVICESERVICE_QNAME);
    }

    public SoapShippingServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPSHIPPINGSERVICESERVICE_QNAME, features);
    }

    public SoapShippingServiceService(URL wsdlLocation) {
        super(wsdlLocation, SOAPSHIPPINGSERVICESERVICE_QNAME);
    }

    public SoapShippingServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPSHIPPINGSERVICESERVICE_QNAME, features);
    }

    public SoapShippingServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapShippingServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISoapShippingService
     */
    @WebEndpoint(name = "SoapShippingServicePort")
    public ISoapShippingService getSoapShippingServicePort() {
        return super.getPort(new QName("shipping.soap.ws.atod.afcepf.fr", "SoapShippingServicePort"), ISoapShippingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISoapShippingService
     */
    @WebEndpoint(name = "SoapShippingServicePort")
    public ISoapShippingService getSoapShippingServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("shipping.soap.ws.atod.afcepf.fr", "SoapShippingServicePort"), ISoapShippingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPSHIPPINGSERVICESERVICE_EXCEPTION!= null) {
            throw SOAPSHIPPINGSERVICESERVICE_EXCEPTION;
        }
        return SOAPSHIPPINGSERVICESERVICE_WSDL_LOCATION;
    }

}
