
package fr.afcepf.atod.wine.business.ws.orchestrator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CommandePortType", targetNamespace = "http://afcepf.fr")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    fr.afcepf.atod.wine.business.ws.paypal.ObjectFactory.class,
    fr.afcepf.atod.wine.business.ws.shipping.ObjectFactory.class,
    fr.afcepf.atod.wine.business.ws.gestionstock.ObjectFactory.class,
    fr.afcepf.atod.wine.business.ws.orchestrator.ObjectFactory.class
})
public interface CommandePortType {


    /**
     * 
     * @param payload
     * @return
     *     returns fr.afcepf.CommandeResponse
     */
    @WebMethod(action = "http://afcepf.fr/process")
    @WebResult(name = "CommandeResponse", targetNamespace = "http://afcepf.fr", partName = "payload")
    public CommandeResponse process(
        @WebParam(name = "CommandeRequest", targetNamespace = "http://afcepf.fr", partName = "payload")
        CommandeRequest payload);

}
