
package fr.afcepf.atod.wine.business.ws.orchestrator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Commande", targetNamespace = "http://afcepf.fr", wsdlLocation = "http://192.168.102.34:8080/ode/processes/Commande?wsdl")
public class Commande
    extends Service
{

    private final static URL COMMANDE_WSDL_LOCATION;
    private final static WebServiceException COMMANDE_EXCEPTION;
    private final static QName COMMANDE_QNAME = new QName("http://afcepf.fr", "Commande");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.102.34:8080/ode/processes/Commande?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMMANDE_WSDL_LOCATION = url;
        COMMANDE_EXCEPTION = e;
    }

    public Commande() {
        super(__getWsdlLocation(), COMMANDE_QNAME);
    }

    public Commande(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMMANDE_QNAME, features);
    }

    public Commande(URL wsdlLocation) {
        super(wsdlLocation, COMMANDE_QNAME);
    }

    public Commande(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMMANDE_QNAME, features);
    }

    public Commande(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Commande(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CommandePortType
     */
    @WebEndpoint(name = "CommandePort")
    public CommandePortType getCommandePort() {
        return super.getPort(new QName("http://afcepf.fr", "CommandePort"), CommandePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommandePortType
     */
    @WebEndpoint(name = "CommandePort")
    public CommandePortType getCommandePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://afcepf.fr", "CommandePort"), CommandePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMMANDE_EXCEPTION!= null) {
            throw COMMANDE_EXCEPTION;
        }
        return COMMANDE_WSDL_LOCATION;
    }

}
