
package fr.afcepf.wine.paypal;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExpressCheckoutServiceService", targetNamespace = "http://paypal.wine.afcepf.fr", wsdlLocation = "http://localhost:28080/Wine-Payment-1.0.0/expressCheckoutService?wsdl")
public class ExpressCheckoutServiceService
    extends Service
{

    private final static URL EXPRESSCHECKOUTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException EXPRESSCHECKOUTSERVICESERVICE_EXCEPTION;
    private final static QName EXPRESSCHECKOUTSERVICESERVICE_QNAME = new QName("http://paypal.wine.afcepf.fr", "ExpressCheckoutServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:28080/Wine-Payment-1.0.0/expressCheckoutService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXPRESSCHECKOUTSERVICESERVICE_WSDL_LOCATION = url;
        EXPRESSCHECKOUTSERVICESERVICE_EXCEPTION = e;
    }

    public ExpressCheckoutServiceService() {
        super(__getWsdlLocation(), EXPRESSCHECKOUTSERVICESERVICE_QNAME);
    }

    public ExpressCheckoutServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXPRESSCHECKOUTSERVICESERVICE_QNAME, features);
    }

    public ExpressCheckoutServiceService(URL wsdlLocation) {
        super(wsdlLocation, EXPRESSCHECKOUTSERVICESERVICE_QNAME);
    }

    public ExpressCheckoutServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXPRESSCHECKOUTSERVICESERVICE_QNAME, features);
    }

    public ExpressCheckoutServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExpressCheckoutServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IExpressCheckout
     */
    @WebEndpoint(name = "ExpressCheckoutServicePort")
    public IExpressCheckout getExpressCheckoutServicePort() {
        return super.getPort(new QName("http://paypal.wine.afcepf.fr", "ExpressCheckoutServicePort"), IExpressCheckout.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IExpressCheckout
     */
    @WebEndpoint(name = "ExpressCheckoutServicePort")
    public IExpressCheckout getExpressCheckoutServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://paypal.wine.afcepf.fr", "ExpressCheckoutServicePort"), IExpressCheckout.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXPRESSCHECKOUTSERVICESERVICE_EXCEPTION!= null) {
            throw EXPRESSCHECKOUTSERVICESERVICE_EXCEPTION;
        }
        return EXPRESSCHECKOUTSERVICESERVICE_WSDL_LOCATION;
    }

}
