
package fr.afcepf.wine.paypal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PayPalRESTException", targetNamespace = "http://paypal.wine.afcepf.fr")
public class PayPalRESTException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PayPalRESTException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PayPalRESTException_Exception(String message, PayPalRESTException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PayPalRESTException_Exception(String message, PayPalRESTException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fr.afcepf.wine.paypal.PayPalRESTException
     */
    public PayPalRESTException getFaultInfo() {
        return faultInfo;
    }

}
